### ISSUE TITLE
Lukki Legs (Spider)

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [spookymilk/Milk-Menu#1]
Hi there,

Would you consider making a mode for the Lukki perk such as this? (It’s broken and I really loved this mod.)

https://modworkshop.net/mydownloads.php?action=view_down&did=25988

“This mod replaces the Lukki Mutation perk.

Removed the leg attack because you are never close enough to enemies for that to be useful.

**Added the ability to climb and hang from stuff without falling.** 

Note: while climbing up you will still use jetpack fuel, however, if your legs are attached to something you will recharge like you are on the ground. I will continue to look for a solution to not use any fuel if the legs are attached to a surface.”

I’m hoping for the ability to hang indefinitely without any loss of jetpack, no key pressing, just hanging like the old mod. (You can still fly too.)

Also, did the older version support wand generation? If not, can clockwork-menu be used with cheatgui that supports that?

Edit: someone helped me in the Noita discord with the broken mod, but I do think it would be a cool edition to your spider mod under Player.

**Comment by spookymilk** [comment]
> Hi there,
> 
> Would you consider making a mode for the Lukki perk such as this? (It’s broken and I really loved this mod.)
> 
> https://modworkshop.net/mydownloads.php?action=view_down&did=25988
> 
> “This mod replaces the Lukki Mutation perk.
> 
> Removed the leg attack because you are never close enough to enemies for that to be useful.
> 
> **Added the ability to climb and hang from stuff without falling.**
> 
> Note: while climbing up you will still use jetpack fuel, however, if your legs are attached to something you will recharge like you are on the ground. I will continue to look for a solution to not use any fuel if the legs are attached to a surface.”
> 
> I’m hoping for the ability to hang indefinitely without any loss of jetpack, no key pressing, just hanging like the old mod. (You can still fly too.)
> 
> Also, did the older version support wand generation? If not, can clockwork-menu be used with cheatgui that supports that?
> 
> Edit: someone helped me in the Noita discord with the broken mod, but I do think it would be a cool edition to your spider mod under Player.

The older version didn't support wand generation, but I plan on eventually adding it in the future.
Currently i'm away for the holidays so I won't be able to really add things for a couple days, but I wasn't aware that this lukki mod existed but if its easy to implement i'll be glad to add it to the next update.

I would say to expect the lukki features around Jan 4th-5th and the wand generation to follow shortly after.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Hey, Spooky. I know you’re probably busy, but I was wondering if you’d figured out how to add this? I do have a working version of the mod I mentioned earlier.

**Comment by spookymilk** [comment]
Hey, I wish I was busy haha, i’m pretty positive that I could add it its
just that my computer went on me during the time I was away. I’m saving up
currently to get a new one, i’ll be sure to add the feature though when I
do get ahold of a new laptop.

If I were to give it a time period it’d probably be a month or two from now
which sucks, but when I do get back onto it i’ll be pushing a big update
including this feature.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
https://files.catbox.moe/0kb2po.zip is the working version, hopefully you’ll get some time to look at it.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Oh I see, best of luck and thanks for your hard work. https://files.catbox.moe/0kb2po.zip is the fixed version from kermit on the discord, for some reason I can’t edit my posts.
